import sys

sys.path.append('/home/ph504/Desktop/Projects/Teleoperation-Interface/src/test/src/')

# doesn't serve too much purpose for now, consider removing if no further functionality is added.

EVENTS = {
    "FREEZE": "freeze",
    "UNFREEZE": "unfreeze",
    "FREEZE_ALL": "freeze_all",
    "UNFREEZE_ALL": "unfreeze_all",
    "CALIBRATE": "calibrate",
    "CALIBRATE_PAUSE": "calibrate_pause",
    "JOY": "joy",
    "COLLISION": "collision",
    "CONGRATULATIONS": "congratulations",
    "COUNTDOWN": "countdown",
    "TRY_AGAIN": "try_again",
    "CLEAR_WAIT_FLAG": "clear_wait_flag",
    "USER_RESET": "user_reset",
    "YELLOW_MODE": "yellow_mode",
    "RED_INIT_MODE": "red_init_mode",
    "STEP_ERROR_DANGER": "step_error_danger",
    "ASSISTED_SECOND": "assisted_second",
    "START_CNTDOWN": "start_cntdwn",
    "STATE_INITIALIZING": "state_initializing",
    "STATE_START": "state_start",
    "STATE_DANGER1_START": "state_danger1_start",
    "STATE_DANGER1_END": "state_danger1_end",
    "STATE_DANGER2_START": "state_danger2_start",
    "STATE_DANGER2_END": "state_danger2_end",
    "STATE_DECISION_PROMPT": "state_decision_prompt",
    "STATE_DECISION_OUTCOME": "state_decision_outcome",
    "STATE_DANGER3_START": "state_danger3_start",
    "STATE_DANGER3_END": "state_danger3_end",
    "STATE_TERMINATION": "state_termination",
    "MANUAL_SECOND": "manual_second",
    "MOVE_BAR_BACKWARD": "move_bar_backward",
    "BAR_SLOW_MODE": "bar_slow_mode",
    "BAR_FAST_MODE": "bar_fast_mode",
    "BAR_ULTRA_MODE": "bar_ultra_mode",
    "COLOR_TRANS": "color_trans",
    "MISTAKE": "mistake",
    "TALKING_STARTED": "talking_started",
    "TALKING_ENDED": "talking_ended",
    "TALKING_STARTED_SAD": "talking_started_sad",
    "STOP_TALKING": "stop_talking",
    "COUNT_MANUAL_TRANS_DEACTIVE": "count_manual_trans_deactive",
    "COUNT_MANUAL_TRANS_ACTIVE": "count_manual_trans_active",
    "RED_MODE": "red_mode",
    "BUTTON_ACTIVATE": "button_activate",
    "CALIBRATE_START": "calibrate_start",
    "TASK_COUNT": "task_count",
    "STEP_ERROR": "step_error",
    "THRESHOLD_CROSS": "threshold_cross",
    "THRESHOLD_CROSS_DANGER": "threshold_cross_danger",
    "COLLISION_HIT": "collision_hit",
    "WRONG_ENTRY": "wrong_entry",
    "DUPLICATE_ENTRY": "duplicate_entry",
    "LABEL_CAMERA_SWITCH": "label_camera_switch",
    "TOGGLE_BAR": "toggle_bar"
}

# Example usage:
# print(EVENTS["FREEZE"])  # Outputs: "freeze"
